TaskList/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskList.Models;

namespace TaskList.Controllers
{
	[Authorize]
    public class InformationController : Controller
    {
        private InformationDataContext Infodb = new InformationDataContext();
        private IllnessDataContext illDB = new IllnessDataContext();

        object _lock = new object();

        // GET: Information
        public ActionResult Index()
        {
            lock (_lock)
            {

                var informations = Infodb.Informations.Where(i => i.Active);

                var illness = illDB.Illnesses.Where(i => i.StillSick);
                ViewBag.Ill = illness;

                return View(informations.ToList().OrderByDescending(x=>x.Id));
            }
            
        }

        [Authorize]
        public ActionResult DeactivateInformation(int id)
        {
            lock (_lock)
            {
                Information information = Infodb.Informations.FirstOrDefault(i => i.Id == id);
                information.Active = false;

                Infodb.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreateInformation()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateInformation(string title, string content)
        {
            lock (_lock)
            {
                Information info = new Information();
                info.Active = true;
                info.Title = title;
                info.Content = content;
                info.Created = DateTime.Now;

                Infodb.Informations.InsertOnSubmit(info);
                Infodb.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult ReportIll()
        {
            return View();
        }

		[Authorize]
		public ActionResult FreshById(int id)
        {
            lock (_lock)
            {
                var person = illDB.Illnesses.FirstOrDefault(p => p.Id == id);
                if (person != null)
                {
                    person.StillSick = false;
                    person.EndDate = DateTime.Now;
                    illDB.SubmitChanges();
                }
            }
            return RedirectToAction("Index");
        }

		[Authorize]
		[HttpPost]
        public ActionResult IsIll(string name)
        {
            Illness ill = new Illness();
            ill.Name = name;
            ill.StillSick = true;
            ill.StartDate = DateTime.Now;
            illDB.Illnesses.InsertOnSubmit(ill);
            illDB.SubmitChanges();

            return RedirectToAction("Index");
        }

		[Authorize]
		[HttpGet]
        public ActionResult IsIll()
        {
            return View();
        }
    }
}

TaskList/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskList.Models;

namespace TaskList.Controllers
{
	[Authorize]
    public class SummaryController : Controller
    {

		private SummaryListDataContext db = new SummaryListDataContext();
		object _lock = new object();

		// GET: Summary
		public ActionResult Index()
        {
			lock (_lock)
			{
				var tables = from t in db.Tables
							 orderby t.EntryDate
							 descending
							 select t;
				return View(tables.ToList());
			}
		}

		//[Authorize]
		//public ActionResult NewSummary(string taskTitle, string taskDescription, string taskAuthor)
		//{
		//	lock (_lock)
		//	{
		//		//Add the new summary to database
		//		Table newTable = new Table();
		//		newTable.Title = taskTitle;
		//		newTable.Description = taskDescription;
		//		newTable.EntryDate = DateTime.Now;
		//		newTable.Author = taskAuthor;

		//		db.Tables.InsertOnSubmit(newTable);
		//		db.SubmitChanges();
		//	}

		//	return RedirectToAction("Index");
		//}

		[Authorize]
		//Display a form for creating a new summary
		public ActionResult Create()
		{
			var member = new ApplicationDbContext();
			ViewBag.member = member.Users.ToList();
			return View();
		}

		public ActionResult Cancel()
		{
			return RedirectToAction("Index");
		}

		[Authorize]
		//Adding a new summary to the database
		public ActionResult CreateNew(string taskTitle, string taskDescription, string taskAuthor)
		{
			lock (_lock)
			{
				//Add the new task to database
				Table newTable = new Table();
				newTable.Title = taskTitle;
				newTable.Description = taskDescription;
				newTable.Author = taskAuthor;
				newTable.EntryDate = DateTime.Now;
				newTable.IsActive = true;

				db.Tables.InsertOnSubmit(newTable);
				db.SubmitChanges();
			}

			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			lock (_lock)
			{
				Table table = db.Tables.FirstOrDefault(i => i.Id == id);
				table.IsActive = false;

				db.SubmitChanges();
			}
			return RedirectToAction("Index");
		}
	}
}

TaskList/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace TaskList.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

TaskList/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

TaskList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - iTaskU</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/myCSS.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
			@if (User.Identity.Name != "Guest")
			{
                @Html.ActionLink("iTaskU", "Index", "Information", new { area = "" }, new { @class = "navbar-brand" })
			}
			else
            {
				@Html.ActionLink("iTaskU", "Index", new { area = "" }, new { @class = "navbar-brand" })
			}
			</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
				@if (User.Identity.Name != "Guest")
				{
					<li>@Html.ActionLink("Information", "Index", "Information")</li>				
					<li>@Html.ActionLink("Opgaver", "Index", "Home")</li>				
					<li>@Html.ActionLink("Referater", "Index", "Summary")</li>
				}
				else
				{
					<li>@Html.ActionLink("Information", "Index", "Information")</li>
					<li>@Html.ActionLink("Opgaver", "Index", "Home")</li>
				}
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - iTaskU by <a href="mailto:reaverdk@live.dk"> Adam Czerwinski</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaskList/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}